export { default as AppMain } from './AppMain'
// export { default as Navbar } from './Navbar'
// export { default as Settings } from './Settings'
// export { default as AppSideBar } from './AppSideBar.vue'
export { default as AppSideBar } from './Sidebar'
// export { default as TagsView } from './TagsView/index.vue'
export { default as AppHeader } from './AppHeader.vue'
export { default as AppFooter } from './AppFooter.vue'
